jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cognitive_exercises_dev?serverTimezone=UTC
    username: cognitive_exercises_dev_user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false